### PR TITLE
feature - DisplayByteSize

### PR DESCRIPTION
**Pull request by kukrik**
Files or image file sizes in bytes are very uncomfortable to read or calculate. The function is created for human readability.
Example:
`$this->lblMessage->Text = 'Thanks for uploading the file: ' . $this->flaSample->FileName . ". File size: " . QString::DisplayByteSize($this->flaSample->Size, 2);`

### CODE REVIEW

**Comment by kukrik** [comment]
At the moment, I was thinking that this feature could be further simplified. I'm giving one example:
```php
public static function FormatFileSize($intBytes) {
    if (is_null($intBytes)) return QApplication::Translate('n/a');
    if ($intBytes == 0) return QApplication::Translate('0 KB');
    if ($intBytes < 0) return QApplication::Translate('-');

    if ($intBytes >= 1073741824) {
        return round($intBytes / 1073741824, 2) . ' ' . QApplication::Translate('GB');
    }

    if ($intBytes >= 1048576) {
        return round($intBytes / 1048576, 2) . ' ' . QApplication::Translate('MB');
    }

    if ($intBytes >= 1024) {
        return round($intBytes / 1024, 2) . ' ' . QApplication::Translate('KB');
    }

    return $intBytes . ' ' . QApplication::Translate('bytes');
}
```
Or leave my first feature? What do you think?

**Comment by matthiaz** [comment]
I like your second version better since it takes into account the translations. But I believe it is still too complex. 
How about something like this?

```
public static function ToHumanReadableFileSize($bytes, $decimals = 2) {
    $size = array('B','kB','MB','GB','TB','PB','EB','ZB','YB');
    $factor = floor((strlen($bytes) - 1) / 3);
    return sprintf("%.{$decimals}f", $bytes / pow(1024, $factor)) . QApplication::Translate($size[$factor]);
}
```

**Comment by kukrik** [comment]
@matthiaz, your last-last solution seems to be elegant...

**Comment by matthiaz** [comment]
@kukrik feel free to update your pull request to reflect this.

**Comment by kukrik** [comment]
> @matthiaz, your last-last solution seems to be elegant...

The ToHumanReadableFileSize() function you are offering is much better. What do you think?

**Comment by matthiaz** [comment]
@kukrik sorry about the late merge. But it's done

**Pull request merged**
