### PR TITLE
Added function GenerateSlug()

### PR DESCRIPTION
**Pull request by kukrik**
Added function GenerateSlug(). Please refer to the issue:
https://github.com/qcubed/qcubed/issues/1175

### CODE REVIEW

**Comment by vaibhav-kaushal** [comment]
It is working as expected. Thanks :) However it did not convert this character: 'æ'

Also, can we change the name of function from 'GenerateSlug' to 'SanitizeForUrl'? I think it suits more.

**Comment by vaibhav-kaushal** [comment]
Also, the indentation is wrong. Please fix indentation. Rest it is working fine :+1:

**Comment by kukrik** [comment]
@vaibhav-kaushal, Thanks! I do not see the problem that change the name of function from 'GenerateSlug' to 'SanitizeForUrl' :)! I fix indentation.

Please indicate where and in which the line is not working as expected that did not convert this character: 'æ'. Or can you send some text to I get some tests done?

**Comment by kukrik** [comment]
I haven't found a better Non-ASCII characters. I was use this page: https://terpconnect.umd.edu/~zben/Web/CharSet/htmlchars.html
Here is a screenshot:
screen shot 2017-02-22 at 22 36 05
Is the test satisfactory?

**Pull request closed without merging**
