### PR TITLE
Refactor Base64Encode and Base64Decode methods in QCryptography

### PR DESCRIPTION
**Pull request by vaibhav-kaushal**
Changes:
 - Move the methods to QString class.
 - Documentation 

Solves #1160

### CODE REVIEW

**Comment by vaibhav-kaushal** [comment]
Will merge this in case no one points out problem with it.

**Comment by spekary** [comment]
Please hold off. I use those routines, so I need to make sure. Just in the middle of a deadline currently.

**Comment by spekary** [comment]
Also, this is a breaking change, so should be merged into 3.1. Or, you can put stubs in QCryptography that point to the new code and deprecate those stubs in the comment so that anyone using those routines directly will not break. In that case, it can be merged into 3.0.

**Comment by vaibhav-kaushal** [comment]
@spekary Stubs makes most sense. Let me update the PR.

**Comment by vaibhav-kaushal** [comment]
@spekary Done.

**Comment by vaibhav-kaushal** [comment]
It has been a week and all the requirements have been met. @spekary Awaiting your confirmation.

**Pull request merged**
