### PR TITLE
Renewed commits  'SanitizeForUrl'

### PR DESCRIPTION
**Pull request by kukrik**
The function is renamed from 'GenerateSlug' to 'SanitizeForUrl'
Indentations are verified.

### CODE REVIEW

**Comment by kukrik** [comment]
Sorry, something went shift... Reference: https://github.com/qcubed/qcubed/pull/1176. We will continue to further here.

@vaibhav-kaushal, We must adhere to accepted generally indentations for QCubed, whether is not it so?

**Comment by kukrik** [comment]
@spekary, You're so far been quiet :). Do not you want to comment?

**Comment by spekary** [comment]
I fixed up some of the comments and function names. Can you add a unit test? Nothing big, just something short that demonstrates what you are trying to do.

**Comment by kukrik** [comment]
@spekary, thank you! I will try next week to make the unit test.

**Comment by vaibhav-kaushal** [comment]
This PR has conflicts. @kukrik

**Comment by kukrik** [comment]
@vaibhav-kaushal, This is your fault :). Please look at your code line 418. There is a superfluous "}".

**Pull request merged**
