### PR TITLE
Add script codegen_cli.php

### PR DESCRIPTION
**Pull request by lackovic10**
The goals of this PR is to add a script which enables codegen execution from the cli
- [x] add `/assets/php/_devtools/codegen_cli.php`
- [x] add description to the `_README.txt` file

### CODE REVIEW

**Comment by lackovic10** [comment]
@spekary can you please add a wip label ?

**Comment by lackovic10** [comment]
thanks @spekary, would it be possible for us to assign labels ?
this PR is ready for review

**Comment by olegabr** [comment]
how we can test it? may be use it in travis test script?

**Comment by olegabr** [comment]
see here: https://github.com/qcubed/framework/blob/beta-3.0/travis/test.php#L34

**Comment by lackovic10** [comment]
are you testing the codegen class somewhere ?

**Comment by lackovic10** [comment]
@olegabr i've checked `codegen.inc.php`
i don't think we should run the codegen again in the travis test, the codegen already seems to be ran there
i suggest merging this, and that codegen itself needs proper tests (if there aren't any already) and those can be added later

**Comment by vaibhav-kaushal** [comment]
I am not sure if Travis will let the tests create files on their system.

**Comment by vaibhav-kaushal** [comment]
@lackovic10 What does this PR actually do? It looks like it runs the codegen via CLI. Is that what it does?

**Comment by lackovic10** [comment]
@vaibhav-kaushal yes, this PR runs codegen from the cli, i've updated the PR description

**Comment by olegabr** [comment]
@lackovic10 please, add a line in the `README` file about motivation to use this tool. After reading this line the user should have an idea in which situation he needs this tool. Thank you!

**Comment by vaibhav-kaushal** [comment]
I think we already have this thing in our _devtools directory somewhere.

**Comment by lackovic10** [comment]
@vaibhav-kaushal looks like there is [codegen.cli](https://github.com/qcubed/framework/blob/beta-3.0/includes/_devtools/codegen.cli)
why does it have the extension `cli` instead of php ?

**Comment by vaibhav-kaushal** [comment]
@lackovic10 I have no idea.

**Comment by vaibhav-kaushal** [comment]
@lackovic10 and @spekary I think this should be in the `project` folder after installation. Which means, it has to be moved to the install directory.

**Pull request closed without merging**
